import JSZip from "jszip";
import type { LessonReel, GeneratedSlide, Slide } from "@shared/schema";

// Script line interface (matches server scriptGenerator.ts)
interface ScriptLine {
    slideId: string;
    slideNumber: number;
    slideType: string;
    text: string;
    pronunciationHints?: string[];
    suggestedDurationSeconds: number;
    startTimeSeconds: number;
}

interface VoiceoverScript {
    lessonTitle: string;
    totalDurationSeconds: number;
    lines: ScriptLine[];
}

// Get slide type label for filename
function getSlideLabel(slide: Slide): string {
    switch (slide.type) {
        case "title": return "title";
        case "hook": return "hook";
        case "objectives": return "objectives";
        case "vocabulary": return `vocab-${(slide as any).term?.toLowerCase().replace(/\s+/g, "-") || "word"}`;
        case "grammar": return "grammar";
        case "reading": return `reading${(slide as any).part ? `-${(slide as any).part}` : ""}`;
        case "example": return "example";
        case "quiz": return `quiz-q${(slide as any).questionNumber || 1}`;
        case "answer": return `answer-q${(slide as any).questionNumber || 1}`;
        case "summary": return "summary";
        case "outro": return "outro";
        default: return slide.type;
    }
}

// Format number with leading zero
function padNumber(num: number): string {
    return num.toString().padStart(2, "0");
}

// Create a ZIP bundle with all slides, scripts, and metadata
export async function createZipBundle(
    reel: LessonReel,
    script?: VoiceoverScript,
    scriptText?: string,
    srtContent?: string,
    renderSlideToCanvas?: (slide: GeneratedSlide, index: number) => Promise<Blob>
): Promise<Blob> {
    const zip = new JSZip();

    // Create folder structure
    const slidesFolder = zip.folder("slides");

    // Add each slide as a PNG
    for (let i = 0; i < reel.slides.length; i++) {
        const genSlide = reel.slides[i];
        const filename = `${padNumber(i + 1)}-${getSlideLabel(genSlide.slide)}.png`;

        if (renderSlideToCanvas) {
            try {
                const blob = await renderSlideToCanvas(genSlide, i);
                slidesFolder?.file(filename, blob);
            } catch (error) {
                console.error(`Failed to render slide ${i + 1}:`, error);
            }
        } else if (genSlide.imageData) {
            // If we have base64 image data, convert it
            const base64Data = genSlide.imageData.split(",")[1];
            if (base64Data) {
                slidesFolder?.file(filename, base64Data, { base64: true });
            }
        }
    }

    // Add script.txt if provided
    if (scriptText) {
        zip.file("script.txt", scriptText);
    }

    // Add captions.srt if provided
    if (srtContent) {
        zip.file("captions.srt", srtContent);
    }

    // Add metadata.json
    const metadata = {
        lessonId: reel.lessonId,
        title: reel.title,
        level: reel.level,
        topic: reel.topic,
        totalSlides: reel.totalSlides,
        generatedAt: new Date().toISOString(),
        slides: reel.slides.map((s, i) => ({
            index: i + 1,
            filename: `${padNumber(i + 1)}-${getSlideLabel(s.slide)}.png`,
            type: s.slide.type,
            hasImage: !!s.imageData,
        })),
        script: script ? {
            totalDurationSeconds: script.totalDurationSeconds,
            totalLines: script.lines.length,
        } : null,
    };
    zip.file("metadata.json", JSON.stringify(metadata, null, 2));

    // Add a README for convenience
    const readme = `# ${reel.title}

## Lesson Info
- **Level**: ${reel.level}
- **Topic**: ${reel.topic}
- **Total Slides**: ${reel.totalSlides}
${script ? `- **Script Duration**: ${Math.floor(script.totalDurationSeconds / 60)}m ${Math.round(script.totalDurationSeconds % 60)}s` : ""}

## Contents
- \`slides/\` - PNG images for each slide (${reel.totalSlides} files)
- \`script.txt\` - Voiceover script with timing cues
- \`captions.srt\` - Subtitle file for video editing
- \`metadata.json\` - Lesson metadata

## How to Use
1. Import slides into Canva Pro or your video editor
2. Use script.txt as your voiceover guide
3. Import captions.srt for auto-subtitles
4. Export as vertical video (9:16) for YouTube Shorts/TikTok

Generated by Lesson Visuals AI
`;
    zip.file("README.md", readme);

    // Generate the ZIP file
    const blob = await zip.generateAsync({
        type: "blob",
        compression: "DEFLATE",
        compressionOptions: { level: 6 },
    });

    return blob;
}

// Download a blob as a file
export function downloadBlob(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

// Create and download a complete lesson bundle
export async function downloadLessonBundle(
    reel: LessonReel,
    script?: VoiceoverScript,
    scriptText?: string,
    srtContent?: string,
    renderSlideToCanvas?: (slide: GeneratedSlide, index: number) => Promise<Blob>
): Promise<void> {
    const blob = await createZipBundle(reel, script, scriptText, srtContent, renderSlideToCanvas);

    // Create filename from lesson title
    const sanitizedTitle = reel.title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "");

    downloadBlob(blob, `${sanitizedTitle}-lesson-bundle.zip`);
}
